version: "3.9"

services:
  mysql:
    image: mysql:8.0
    volumes:
    - type: bind
      source: ./tmp/mysql-data
      target: /var/lib/mysql
    restart: always
    environment:
      - MYSQL_DATABASE=testing
      - MYSQL_ROOT_PASSWORD=123
    ports:
      - '3306:3306'
    networks:
      - cloud-network


#  rabbitmq:
#    image: rabbitmq:3-management-alpine
#    container_name: 'rabbitmq'
#    ports:
#      - '5672:5672'
#      - '15672:15672'
#    volumes:
#      - ./tmp/rabbitmq/:/var/lib/rabbitmq/
#      - ./tmp/rabbitmq/log/:/var/log/rabbitmq
#    networks:
#      - cloud-network


  kafka1:
    image: 'bitnami/kafka:latest'
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=wCRK61mCR7Kg8DmkFDaOng
    volumes:
      - ./tmp/kafka:/bitnami/kafka
    networks:
      - cloud-network


  ui:
    image: provectuslabs/kafka-ui:v0.4.0
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - kafka1
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka1:9092
      - KAFKA_CLUSTERS_0_NAME=kraft
    networks:
      - cloud-network


networks:
  cloud-network:
    driver: bridge